### ISSUE TITLE
Dashboard not displaying info

### ISSUE THREAD

**Issue by bandwith** [SteveKueng/munkiwebadmin#3]
Specific computer update page gives results. 
![screenshot 2015-07-20 09 14 45](https://cloud.githubusercontent.com/assets/62576/8776530/de333eee-2ebf-11e5-9696-764e26a820a3.png)

However, the dashboard is empty.

![screenshot 2015-07-20 09 14 24](https://cloud.githubusercontent.com/assets/62576/8776528/de312ed8-2ebf-11e5-9ba9-3e573c2bd86f.png)
![screenshot 2015-07-20 09 14 31](https://cloud.githubusercontent.com/assets/62576/8776527/de2e3386-2ebf-11e5-90cc-7531134c3a59.png)

**Comment by SteveKueng** [comment]
sorry for the late answer!
Please try the newest version and look at "Permissions" on the wiki pages.
