### ISSUE TITLE
/licenses/available throwing error

### ISSUE THREAD

**Issue by codeskipper** [SteveKueng/munkiwebadmin#4]
Hi, 

When testing with your munkiwebadmin fork, I can't get the License seat tracking to work so the client can if any seats are available.  The URL that the Munki client uses to check for  available  seats to install optional installs, throws an error:

TypeError at /licenses/available/
**init**() got an unexpected keyword argument 'mimetype'
Request Method: GET
Request URL:    https://mwa-host.mysite.lan:8443/licenses/available/?name=Firefox
Django Version: 1.7.2
Exception Type: TypeError
Exception Value:  
**init**() got an unexpected keyword argument 'mimetype'
Exception Location: /usr/local/munkiwebadmin_env/lib/python2.7/site-packages/django/http/response.py in **init**, line 318
Python Executable:  /usr/bin/python
Python Version: 2.7.6
Python Path:  
['/usr/local/munkiwebadmin_env/munkiwebadmin',
 '/usr/local/munkiwebadmin_env',
 '/usr/local/munkiwebadmin_env',
 '/usr/local/munkiwebadmin_env/lib/python2.7/site-packages',
 '/Library/Python/2.7/site-packages/pip-7.1.0-py2.7.egg',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python27.zip',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC',
 '/Library/Python/2.7/site-packages']
Server time:

The above is part of the debug output when running in Apache mod_wsgi and the same occurs in the the development webserver.

I'd like to patch this manually if you could throw me a hint where to look or what to try.  

Cheers,

Martinus

**Comment by SteveKueng** [comment]
Hi Martinus
I fixed this issue in the 0.3 version.
Please try this one!

Cheers,
Steve
