### ISSUE TITLE
Feature: Linux Compatibility for Creating Agent

### ISSUE THREAD

**Issue by mtarleton** [SteveKueng/munkiwebadmin#7]
Hello! 

It would be fantastic if there were versions of the scripts for the client-side reporting agent that would allow them to be run on Linux. I was able to get MWA running happily on Debian but I was unable to complete the steps to get all the fancy reporting in MWA.

**Comment by SteveKueng** [comment]
Hi!

Cool idea! I thought about this with Windows clients...
For some basic information (hostname, serial, ...) just a post request is needed.
All other informations are stored in a plist generated from system report... creating an xml on debian with the correct keys should work...
I attached a script witch dose the very basic stuff and should create a new client in munkiwebadmin. try it :)
[postflight_submit.zip](https://github.com/SteveKueng/munkiwebadmin/files/225399/postflight_submit.zip)

I'm currently working on an new version, where I implement the mwa2 features from gred neagle and I'm also redesign the report functions.

Regards,
Steve
